# Generated by Django 6.0.4 on 2026-08-12 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('symptom1', models.CharField(max_length=100)),
                ('symptom2', models.CharField(max_length=100)),
                ('symptom3', models.CharField(max_length=100)),
                ('symptom4', models.CharField(max_length=100)),
                ('symptom5', models.CharField(max_length=100)),
                ('predicted_disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('top3_predictions', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
