# Generated by Django 6.0.4 on 2026-08-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml65app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('total_beds', models.IntegerField(default=0)),
                ('available_beds', models.IntegerField(default=0)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('doctor_specialization', models.CharField(blank=True, max_length=100)),
                ('doctor_available', models.BooleanField(default=False)),
                ('specializations', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(default=3.0)),
            ],
        ),
        migrations.AlterField(
            model_name='patientprediction',
            name='symptom1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprediction',
            name='symptom2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprediction',
            name='symptom3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprediction',
            name='symptom4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprediction',
            name='symptom5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
