# Generated by Django 6.0.4 on 2026-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml65app', '0002_hospital_alter_patientprediction_symptom1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprediction',
            name='urgency',
            field=models.CharField(blank=True, default='Moderate', max_length=20),
        ),
    ]
